import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import settings

def _send_email(recipient: str, subject: str, body: str) -> bool:
    """
    Internal function to send an email using Gmail SMTP and configuration settings.
    Catches SMTP exceptions and returns True/False to prevent exposing credentials.
    """
    if not settings.ENABLE_EMAIL_NOTIFICATIONS:
        return False

    if not settings.SMTP_USERNAME or not settings.SMTP_PASSWORD:
        print("Warning: SMTP credentials are not configured.")
        return False

    msg = MIMEMultipart()
    msg['From'] = settings.ALERT_FROM_EMAIL
    msg['To'] = recipient
    msg['Subject'] = subject

    msg.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT)
        server.starttls()
        server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
        server.send_message(msg)
        server.quit()
        return True
    except smtplib.SMTPException as e:
        print(f"SMTP error occurred: {e.__class__.__name__}")
        return False
    except Exception as e:
        print(f"An unexpected error occurred while sending email: {e.__class__.__name__}")
        return False

def send_test_email(recipient: str) -> bool:
    """
    Sends a test email to verify SMTP configuration.
    """
    subject = "AGEISMIND — Email Notification Test"
    body = """AGEISMIND EMAIL NOTIFICATION TEST

This confirms that the AGEISMIND backend
can successfully send email notifications.

Notification System:
Email

Backend:
FastAPI
"""
    return _send_email(recipient, subject, body)

def send_alert_email(recipient: str, alert_data: dict) -> bool:
    """
    Sends an alert email formatting the provided alert data.
    """
    priority = alert_data.get("priority", "UNKNOWN")
    complaint_id = alert_data.get("complaint_id", "UNKNOWN")
    
    subject = f"AGEISMIND — {priority} Predictive Alert — {complaint_id}"
    
    body = f"""This alert represents a predictive investigative lead generated by the AGEISMIND system.

Alert ID: {alert_data.get("alert_id", "N/A")}
Complaint ID: {complaint_id}
Priority: {priority}
Candidate Location: {alert_data.get("withdrawal_location_id", "N/A")}
District: {alert_data.get("district", "N/A")}
Predicted Probability: {alert_data.get("probability", "N/A")}
Model Version: 1.0.0
Generated Time: {alert_data.get("created_at", "N/A")}

The predicted location is not confirmation of criminal activity."""

    return _send_email(recipient, subject, body)
