"""Add alerts table

Revision ID: ce7eb22492ea
Revises: f8fdb7e6cc7e
Create Date: 2026-09-10 21:11:23.313006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7eb22492ea'
down_revision: Union[str, None] = 'f8fdb7e6cc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('prediction_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('alerts')
    # ### end Alembic commands ###
