"""tamil_nadu_geography

Revision ID: de76a04a8eaa
Revises: 001
Create Date: 2026-09-09 19:41:08.197485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'de76a04a8eaa'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_districts_district_name'), 'districts', ['district_name'], unique=True)
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('city_or_town', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_district_id'), 'locations', ['district_id'], unique=False)
    op.drop_index(op.f('ix_account_relationships_source'), table_name='account_relationships')
    op.drop_index(op.f('ix_account_relationships_target'), table_name='account_relationships')
    op.create_index(op.f('ix_account_relationships_source_account'), 'account_relationships', ['source_account'], unique=False)
    op.create_index(op.f('ix_account_relationships_target_account'), 'account_relationships', ['target_account'], unique=False)
    op.add_column('accounts', sa.Column('district_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_accounts_district_id'), 'accounts', ['district_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'districts', ['district_id'], ['district_id'], ondelete='CASCADE')
    op.add_column('complaints', sa.Column('district_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_complaints_district_id'), 'complaints', ['district_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'districts', ['district_id'], ['district_id'], ondelete='CASCADE')
    op.add_column('historical_cases', sa.Column('district_id', sa.String(length=50), nullable=False))
    op.add_column('historical_cases', sa.Column('latitude', sa.Numeric(precision=9, scale=4), nullable=False))
    op.add_column('historical_cases', sa.Column('longitude', sa.Numeric(precision=9, scale=4), nullable=False))
    op.create_index(op.f('ix_historical_cases_district_id'), 'historical_cases', ['district_id'], unique=False)
    op.create_foreign_key(None, 'historical_cases', 'districts', ['district_id'], ['district_id'], ondelete='CASCADE')
    op.add_column('withdrawal_locations', sa.Column('district_id', sa.String(length=50), nullable=False))
    op.add_column('withdrawal_locations', sa.Column('location_reference_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_withdrawal_locations_district_id'), 'withdrawal_locations', ['district_id'], unique=False)
    op.create_foreign_key(None, 'withdrawal_locations', 'locations', ['location_reference_id'], ['location_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'withdrawal_locations', 'districts', ['district_id'], ['district_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawal_locations', type_='foreignkey')
    op.drop_constraint(None, 'withdrawal_locations', type_='foreignkey')
    op.drop_index(op.f('ix_withdrawal_locations_district_id'), table_name='withdrawal_locations')
    op.drop_column('withdrawal_locations', 'location_reference_id')
    op.drop_column('withdrawal_locations', 'district_id')
    op.drop_constraint(None, 'historical_cases', type_='foreignkey')
    op.drop_index(op.f('ix_historical_cases_district_id'), table_name='historical_cases')
    op.drop_column('historical_cases', 'longitude')
    op.drop_column('historical_cases', 'latitude')
    op.drop_column('historical_cases', 'district_id')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_district_id'), table_name='complaints')
    op.drop_column('complaints', 'district_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_district_id'), table_name='accounts')
    op.drop_column('accounts', 'district_id')
    op.drop_index(op.f('ix_account_relationships_target_account'), table_name='account_relationships')
    op.drop_index(op.f('ix_account_relationships_source_account'), table_name='account_relationships')
    op.create_index(op.f('ix_account_relationships_target'), 'account_relationships', ['target_account'], unique=False)
    op.create_index(op.f('ix_account_relationships_source'), 'account_relationships', ['source_account'], unique=False)
    op.drop_index(op.f('ix_locations_district_id'), table_name='locations')
    op.drop_index('idx_locations_geometry', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    op.drop_index(op.f('ix_districts_district_name'), table_name='districts')
    op.drop_index('idx_districts_geometry', table_name='districts', postgresql_using='gist')
    op.drop_table('districts')
    # ### end Alembic commands ###
