"""
===============================================================================
SYNTHETIC PROTOTYPE DATA GENERATOR (TAMIL NADU ARCHITECTURE)
AI-Driven Cybercrime Cash Withdrawal Prediction System
===============================================================================

DISCLAIMER:
    All data generated by this script is SYNTHETIC PROTOTYPE DATA.
    It does NOT contain real citizen data, real bank account data, or data
    from any government portal. It is intended solely for prototype
    demonstration and development purposes.

    The geographical data specifically targets the 38 districts of Tamil Nadu.
"""

import csv
import os
import random
import string
from datetime import datetime, timedelta
from collections import defaultdict

# ===========================================================================
# FIXED RANDOM SEED FOR DETERMINISTIC REPRODUCTION
# ===========================================================================
SEED = 42
random.seed(SEED)

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")

for d in [RAW_DIR, PROCESSED_DIR]:
    os.makedirs(d, exist_ok=True)

# ===========================================================================
# TAMIL NADU DISTRICTS (38 Official Districts with approximate centers)
# ===========================================================================
TAMIL_NADU_DISTRICTS = [
    {"id": "TN01", "name": "Ariyalur", "lat": 11.1400, "lon": 79.0786},
    {"id": "TN02", "name": "Chengalpattu", "lat": 12.6939, "lon": 79.9757},
    {"id": "TN03", "name": "Chennai", "lat": 13.0827, "lon": 80.2707},
    {"id": "TN04", "name": "Coimbatore", "lat": 11.0168, "lon": 76.9558},
    {"id": "TN05", "name": "Cuddalore", "lat": 11.7480, "lon": 79.7714},
    {"id": "TN06", "name": "Dharmapuri", "lat": 12.1277, "lon": 78.1582},
    {"id": "TN07", "name": "Dindigul", "lat": 10.3624, "lon": 77.9695},
    {"id": "TN08", "name": "Erode", "lat": 11.3410, "lon": 77.7172},
    {"id": "TN09", "name": "Kallakurichi", "lat": 11.7383, "lon": 78.9639},
    {"id": "TN10", "name": "Kancheepuram", "lat": 12.8342, "lon": 79.7036},
    {"id": "TN11", "name": "Karur", "lat": 10.9601, "lon": 78.0766},
    {"id": "TN12", "name": "Krishnagiri", "lat": 12.5186, "lon": 78.2137},
    {"id": "TN13", "name": "Madurai", "lat": 9.9252, "lon": 78.1198},
    {"id": "TN14", "name": "Mayiladuthurai", "lat": 11.1085, "lon": 79.6534},
    {"id": "TN15", "name": "Nagapattinam", "lat": 10.7672, "lon": 79.8449},
    {"id": "TN16", "name": "Kanniyakumari", "lat": 8.0883, "lon": 77.5385},
    {"id": "TN17", "name": "Namakkal", "lat": 11.2189, "lon": 78.1674},
    {"id": "TN18", "name": "Perambalur", "lat": 11.2342, "lon": 78.8821},
    {"id": "TN19", "name": "Pudukkottai", "lat": 10.3797, "lon": 78.8205},
    {"id": "TN20", "name": "Ramanathapuram", "lat": 9.3639, "lon": 78.8321},
    {"id": "TN21", "name": "Ranipet", "lat": 12.9272, "lon": 79.3333},
    {"id": "TN22", "name": "Salem", "lat": 11.6643, "lon": 78.1460},
    {"id": "TN23", "name": "Sivaganga", "lat": 9.8433, "lon": 78.4809},
    {"id": "TN24", "name": "Tenkasi", "lat": 8.9564, "lon": 77.3151},
    {"id": "TN25", "name": "Thanjavur", "lat": 10.7870, "lon": 79.1378},
    {"id": "TN26", "name": "Theni", "lat": 10.0104, "lon": 77.4768},
    {"id": "TN27", "name": "Tiruvallur", "lat": 13.1402, "lon": 79.9071},
    {"id": "TN28", "name": "Tiruvarur", "lat": 10.7661, "lon": 79.6344},
    {"id": "TN29", "name": "Thoothukudi", "lat": 8.7642, "lon": 78.1348},
    {"id": "TN30", "name": "Tiruchirappalli", "lat": 10.7905, "lon": 78.7047},
    {"id": "TN31", "name": "Tirunelveli", "lat": 8.7139, "lon": 77.7567},
    {"id": "TN32", "name": "Tirupathur", "lat": 12.4937, "lon": 78.5661},
    {"id": "TN33", "name": "Tiruppur", "lat": 11.1085, "lon": 77.3411},
    {"id": "TN34", "name": "Tiruvannamalai", "lat": 12.2253, "lon": 79.0747},
    {"id": "TN35", "name": "The Nilgiris", "lat": 11.4916, "lon": 76.7337},
    {"id": "TN36", "name": "Vellore", "lat": 12.9165, "lon": 79.1325},
    {"id": "TN37", "name": "Viluppuram", "lat": 11.9401, "lon": 79.4861},
    {"id": "TN38", "name": "Virudhunagar", "lat": 9.5872, "lon": 77.9624},
]

FRAUD_TYPES = ["UPI Fraud", "Phishing", "OTP Fraud", "SIM Swap", "Loan Fraud", "Investment Scam", "Job Fraud", "Card Skimming", "Identity Theft", "Romance Scam"]
CRIME_CATEGORIES = ["Online Financial Fraud", "Social Engineering", "Identity Fraud", "Banking Fraud", "Cyber Deception"]
SOURCE_CHANNELS = ["National Cybercrime Portal", "State Police Portal", "Bank Referral", "Helpline 1930", "Walk-in Complaint"]
COMPLAINT_STATUSES = ["Under Investigation", "FIR Filed", "Chargesheet Filed", "Resolved", "Pending Review"]
ACCOUNT_TYPES = ["Savings", "Current", "Jan Dhan", "Wallet", "Business"]
ACCOUNT_STATUSES = ["Active", "Frozen", "Suspended", "Under Monitoring", "Closed"]
TRANSACTION_TYPES = ["UPI", "NEFT", "RTGS", "IMPS", "ATM Withdrawal", "Card Payment"]
TRANSACTION_STATUSES = ["Completed", "Pending", "Failed", "Reversed"]
RELATIONSHIP_TYPES = ["Frequent Transactor", "Mule Chain", "Beneficiary", "Co-holder", "Shared Device", "Common IP"]
LOCATION_TYPES = ["CITY", "TOWN", "AREA", "ATM_ZONE", "WITHDRAWAL_ZONE"]
WITHDRAWAL_OUTCOMES = ["Withdrawal Detected", "Withdrawal Attempted", "No Activity"]

# ===========================================================================
# HELPER FUNCTIONS
# ===========================================================================
def jitter(base, spread=0.05):
    return round(base + random.uniform(-spread, spread), 4)

def random_date(start_str="2025-01-01", end_str="2026-08-31"):
    start = datetime.strptime(start_str, "%Y-%m-%d")
    end = datetime.strptime(end_str, "%Y-%m-%d")
    delta = (end - start).days
    d = start + timedelta(days=random.randint(0, delta))
    return d.strftime("%Y-%m-%d")

def random_time():
    return f"{random.randint(0, 23):02d}:{random.randint(0, 59):02d}:{random.randint(0, 59):02d}"

def write_csv(filepath, fieldnames, rows):
    with open(filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

# ===========================================================================
# GENERATORS
# ===========================================================================
def generate_districts():
    rows = []
    for d in TAMIL_NADU_DISTRICTS:
        rows.append({
            "district_id": d["id"],
            "district_name": d["name"],
            "state_name": "Tamil Nadu",
            "latitude": d["lat"],
            "longitude": d["lon"]
        })
    return rows

def generate_locations():
    locations = []
    loc_counter = 1
    for d in TAMIL_NADU_DISTRICTS:
        # Generate 2 to 4 locations per district
        for _ in range(random.randint(2, 4)):
            loc_id = f"LOC{loc_counter:04d}"
            loc_counter += 1
            locations.append({
                "location_id": loc_id,
                "district_id": d["id"],
                "location_name": f"{d['name']} {random.choice(['Central', 'North', 'South', 'East', 'West', 'Market', 'Plaza'])}",
                "city_or_town": d["name"],
                "location_type": random.choice(LOCATION_TYPES),
                "latitude": jitter(d["lat"]),
                "longitude": jitter(d["lon"])
            })
    return locations

def generate_accounts(n=70):
    accounts = []
    used_ids = set()
    for i in range(n):
        acc_id = f"ACC{100001 + i}"
        if acc_id in used_ids: continue
        used_ids.add(acc_id)
        dist = random.choice(TAMIL_NADU_DISTRICTS)
        accounts.append({
            "account_id": acc_id,
            "district_id": dist["id"],
            "account_type": random.choice(ACCOUNT_TYPES),
            "city": dist["name"],
            "latitude": jitter(dist["lat"]),
            "longitude": jitter(dist["lon"]),
            "account_risk_score": round(random.uniform(0.05, 0.98), 2),
            "previous_case_count": random.randint(0, 12),
            "account_status": random.choice(ACCOUNT_STATUSES)
        })
    return accounts

def generate_complaints(n=35):
    complaints = []
    used_ids = set()
    for i in range(n):
        comp_id = f"CC{1001 + i}"
        if comp_id in used_ids: continue
        used_ids.add(comp_id)
        dist = random.choice(TAMIL_NADU_DISTRICTS)
        complaints.append({
            "complaint_id": comp_id,
            "district_id": dist["id"],
            "complaint_date": random_date(),
            "complaint_time": random_time(),
            "fraud_type": random.choice(FRAUD_TYPES),
            "crime_category": random.choice(CRIME_CATEGORIES),
            "fraud_amount": round(random.uniform(1000, 500000), 2),
            "victim_city": dist["name"],
            "victim_latitude": jitter(dist["lat"]),
            "victim_longitude": jitter(dist["lon"]),
            "source_channel": random.choice(SOURCE_CHANNELS),
            "status": random.choice(COMPLAINT_STATUSES)
        })
    return complaints

def generate_transactions(accounts, complaints, n=200):
    txns = []
    acc_ids = [a["account_id"] for a in accounts]
    comp_ids = [c["complaint_id"] for c in complaints]
    for i in range(n):
        txns.append({
            "transaction_id": f"TXN{80001 + i}",
            "complaint_id": random.choice(comp_ids),
            "sender_account": random.choice(acc_ids),
            "receiver_account": random.choice(acc_ids),
            "amount": round(random.uniform(500, 200000), 2),
            "transaction_time": f"{random_date()} {random_time()}",
            "transaction_type": random.choice(TRANSACTION_TYPES),
            "transaction_status": random.choice(TRANSACTION_STATUSES)
        })
    return txns

def generate_relationships(accounts, n=150):
    rels = []
    acc_ids = [a["account_id"] for a in accounts]
    for i in range(n):
        source = random.choice(acc_ids)
        target = random.choice(acc_ids)
        while target == source:
            target = random.choice(acc_ids)
        rels.append({
            "relationship_id": f"REL{20001 + i}",
            "source_account": source,
            "target_account": target,
            "relationship_type": random.choice(RELATIONSHIP_TYPES),
            "total_amount": round(random.uniform(1000, 1000000), 2),
            "transaction_count": random.randint(1, 50)
        })
    return rels

def load_real_withdrawal_locations():
    w_locs = []
    filepath = os.path.join(RAW_DIR, "withdrawal_locations.csv")
    if not os.path.exists(filepath):
        print("ERROR: withdrawal_locations.csv not found! Run fetch_real_atms.py first.")
        return []
    with open(filepath, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            w_locs.append({
                "location_id": row["location_id"],
                "district_id": row["district_id"],
                "location_reference_id": row["location_reference_id"],
                "location_name": row["location_name"],
                "city": row["city"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "atm_count": int(row["atm_count"]),
                "location_type": row["location_type"],
                "area_risk_baseline": float(row["area_risk_baseline"])
            })
    return w_locs

def generate_historical_cases(withdrawal_locations, n=200):
    cases = []
    w_locs = {w["location_id"]: w for w in withdrawal_locations}
    wl_ids = list(w_locs.keys())
    for i in range(n):
        wl = random.choice(wl_ids)
        ref_loc = w_locs[wl]
        cases.append({
            "historical_case_id": f"HC{30001 + i}",
            "district_id": ref_loc["district_id"],
            "withdrawal_location_id": wl,
            "fraud_type": random.choice(FRAUD_TYPES),
            "fraud_amount": round(random.uniform(2000, 300000), 2),
            "transaction_hour": random.randint(0, 23),
            "city": ref_loc["city"],
            "latitude": ref_loc["latitude"],
            "longitude": ref_loc["longitude"],
            "account_risk": round(random.uniform(0.4, 0.99), 2),
            "transaction_velocity": random.randint(2, 25),
            "distance_to_location": round(random.uniform(0.1, 50.0), 2),
            "atm_density": random.randint(1, 20),
            "historical_similarity": round(random.uniform(0.1, 1.0), 2),
            "withdrawal_zone": wl,
            "outcome": random.choice(WITHDRAWAL_OUTCOMES)
        })
    return cases

# ===========================================================================
# CC1001 OVERRIDE (TAMIL NADU ONLY)
# ===========================================================================
def enrich_cc1001(complaints, accounts, transactions, relationships, withdrawal_locations):
    # Retrieve relevant TN districts
    chennai = next(d for d in TAMIL_NADU_DISTRICTS if d["name"] == "Chennai")
    kanchee = next(d for d in TAMIL_NADU_DISTRICTS if d["name"] == "Kancheepuram")
    tiruppur = next(d for d in TAMIL_NADU_DISTRICTS if d["name"] == "Tiruppur")
    coimbatore = next(d for d in TAMIL_NADU_DISTRICTS if d["name"] == "Coimbatore")
    
    # 1. Update CC1001 Complaint
    for comp in complaints:
        if comp["complaint_id"] == "CC1001":
            comp["complaint_date"] = "2026-07-15"
            comp["fraud_type"] = "UPI Fraud"
            comp["fraud_amount"] = 487500.00
            comp["complaint_time"] = "14:32:00"
            comp["district_id"] = chennai["id"]
            comp["victim_city"] = "Chennai"
            comp["victim_latitude"] = chennai["lat"]
            comp["victim_longitude"] = chennai["lon"]
            comp["crime_category"] = "Online Financial Fraud"
            comp["source_channel"] = "Helpline 1930"
            comp["status"] = "Under Investigation"
            break

    # 2. CC1001 Accounts
    cc1001_accounts = [
        {"account_id": "ACC100001", "district_id": chennai["id"], "account_type": "Savings", "city": "Chennai", "latitude": jitter(chennai["lat"]), "longitude": jitter(chennai["lon"]), "account_risk_score": 0.12, "previous_case_count": 0, "account_status": "Active"},
        {"account_id": "ACC100002", "district_id": chennai["id"], "account_type": "Current", "city": "Chennai", "latitude": jitter(chennai["lat"]), "longitude": jitter(chennai["lon"]), "account_risk_score": 0.78, "previous_case_count": 3, "account_status": "Under Monitoring"},
        {"account_id": "ACC100003", "district_id": kanchee["id"], "account_type": "Jan Dhan", "city": "Kancheepuram", "latitude": jitter(kanchee["lat"]), "longitude": jitter(kanchee["lon"]), "account_risk_score": 0.85, "previous_case_count": 5, "account_status": "Frozen"},
        {"account_id": "ACC100004", "district_id": tiruppur["id"], "account_type": "Savings", "city": "Tiruppur", "latitude": jitter(tiruppur["lat"]), "longitude": jitter(tiruppur["lon"]), "account_risk_score": 0.91, "previous_case_count": 7, "account_status": "Suspended"},
        {"account_id": "ACC100005", "district_id": chennai["id"], "account_type": "Wallet", "city": "Chennai", "latitude": jitter(chennai["lat"]), "longitude": jitter(chennai["lon"]), "account_risk_score": 0.67, "previous_case_count": 2, "account_status": "Active"},
        {"account_id": "ACC100006", "district_id": coimbatore["id"], "account_type": "Current", "city": "Coimbatore", "latitude": jitter(coimbatore["lat"]), "longitude": jitter(coimbatore["lon"]), "account_risk_score": 0.72, "previous_case_count": 4, "account_status": "Under Monitoring"},
    ]
    existing_ids = {a["account_id"] for a in accounts}
    for acc in cc1001_accounts:
        if acc["account_id"] not in existing_ids:
            accounts.append(acc)
            existing_ids.add(acc["account_id"])

    # 3. Transactions (10 transactions)
    transactions[:] = [t for t in transactions if t["complaint_id"] != "CC1001"]
    cc1001_txns = [
        {"transaction_id": "TXN90001", "complaint_id": "CC1001", "sender_account": "ACC100001", "receiver_account": "ACC100002", "amount": 150000.00, "transaction_time": "2026-07-14 22:15:00", "transaction_type": "UPI", "transaction_status": "Completed"},
        {"transaction_id": "TXN90002", "complaint_id": "CC1001", "sender_account": "ACC100001", "receiver_account": "ACC100002", "amount": 97500.00, "transaction_time": "2026-07-14 22:18:30", "transaction_type": "UPI", "transaction_status": "Completed"},
        {"transaction_id": "TXN90003", "complaint_id": "CC1001", "sender_account": "ACC100002", "receiver_account": "ACC100003", "amount": 120000.00, "transaction_time": "2026-07-14 23:05:00", "transaction_type": "IMPS", "transaction_status": "Completed"},
        {"transaction_id": "TXN90004", "complaint_id": "CC1001", "sender_account": "ACC100002", "receiver_account": "ACC100004", "amount": 80000.00, "transaction_time": "2026-07-14 23:12:00", "transaction_type": "NEFT", "transaction_status": "Completed"},
        {"transaction_id": "TXN90005", "complaint_id": "CC1001", "sender_account": "ACC100001", "receiver_account": "ACC100005", "amount": 100000.00, "transaction_time": "2026-07-15 00:02:00", "transaction_type": "UPI", "transaction_status": "Completed"},
        {"transaction_id": "TXN90006", "complaint_id": "CC1001", "sender_account": "ACC100005", "receiver_account": "ACC100003", "amount": 60000.00, "transaction_time": "2026-07-15 01:30:00", "transaction_type": "UPI", "transaction_status": "Completed"},
        {"transaction_id": "TXN90007", "complaint_id": "CC1001", "sender_account": "ACC100003", "receiver_account": "ACC100006", "amount": 75000.00, "transaction_time": "2026-07-15 06:45:00", "transaction_type": "RTGS", "transaction_status": "Completed"},
        {"transaction_id": "TXN90008", "complaint_id": "CC1001", "sender_account": "ACC100004", "receiver_account": "ACC100004", "amount": 10000.00, "transaction_time": "2026-07-15 07:00:00", "transaction_type": "ATM Withdrawal", "transaction_status": "Completed"},
        {"transaction_id": "TXN90009", "complaint_id": "CC1001", "sender_account": "ACC100006", "receiver_account": "ACC100006", "amount": 50000.00, "transaction_time": "2026-07-15 08:30:00", "transaction_type": "ATM Withdrawal", "transaction_status": "Failed"},
        {"transaction_id": "TXN90010", "complaint_id": "CC1001", "sender_account": "ACC100005", "receiver_account": "ACC100002", "amount": 25000.00, "transaction_time": "2026-07-15 09:15:00", "transaction_type": "IMPS", "transaction_status": "Completed"}
    ]
    transactions.extend(cc1001_txns)

    # 4. Relationships (fully connected mesh)
    cc_accs = [a["account_id"] for a in cc1001_accounts]
    for i in range(len(cc_accs)):
        for j in range(len(cc_accs)):
            if i != j:
                relationships.append({
                    "relationship_id": f"REL900{i}{j}",
                    "source_account": cc_accs[i],
                    "target_account": cc_accs[j],
                    "relationship_type": random.choice(RELATIONSHIP_TYPES),
                    "total_amount": round(random.uniform(5000, 200000), 2),
                    "transaction_count": random.randint(1, 10)
                })

# ===========================================================================
# MAIN EXECUTOR
# ===========================================================================
if __name__ == "__main__":
    print("Generating Synthetic Prototype Data for Tamil Nadu...")
    
    districts = generate_districts()
    locations = generate_locations()
    accounts = generate_accounts(2000)
    complaints = generate_complaints(1000)
    transactions = generate_transactions(accounts, complaints, 8500)
    relationships = generate_relationships(accounts, 4500)
    withdrawal_locations = load_real_withdrawal_locations()
    historical_cases = generate_historical_cases(withdrawal_locations, 1000)
    
    enrich_cc1001(complaints, accounts, transactions, relationships, withdrawal_locations)
    
    write_csv(os.path.join(RAW_DIR, "districts.csv"), list(districts[0].keys()), districts)
    write_csv(os.path.join(RAW_DIR, "locations.csv"), list(locations[0].keys()), locations)
    write_csv(os.path.join(RAW_DIR, "accounts.csv"), list(accounts[0].keys()), accounts)
    write_csv(os.path.join(RAW_DIR, "complaints.csv"), list(complaints[0].keys()), complaints)
    write_csv(os.path.join(RAW_DIR, "transactions.csv"), list(transactions[0].keys()), transactions)
    write_csv(os.path.join(RAW_DIR, "account_relationships.csv"), list(relationships[0].keys()), relationships)
    write_csv(os.path.join(RAW_DIR, "historical_cases.csv"), list(historical_cases[0].keys()), historical_cases)
    
    print("DONE. Tamil Nadu synthetic datasets written to data/raw/")
